### ISSUE TITLE
memOp weight update

### ISSUE THREAD

**Issue by qingyuanxingsi** [fumin/ntm#2]
I have read the code, I can see that the controller weights are updated by RMSProp, but **where is the memOp weights updated**?? I can see that the gradients of parameters are computed, but they have never been used to update their values. Would you be so kind as to clarify this for me??

**Comment by fumin** [comment]
Hi Qing

Thanks for your question, by "memOp weights" I guess you mean the bias values of the memory bank.
The short answer is since they are part of the weights of the controller https://github.com/fumin/ntm/blob/master/cntl1.go#L102 , they as a result get updated by say RMSProp https://github.com/fumin/ntm/blob/master/ntm.go#L354 , too.
The long answer is that the Controller interface dictates that controllers should expose all learnable parameters through the WeightsVal and friends functions https://github.com/fumin/ntm/blob/master/ntm.go#L128 . The benefit of this is that all weight updating algorithms including SGD, RmsProp etc., can therefore do their own job of updating the parameters without knowing the internal structure and usage of those parameters.
I hope this helps understanding the overall picture a bit.

**Comment by qingyuanxingsi** [comment]
Thanks for your kind reply, I can see that you update all the weights of the Controller using RMSProp(including the bias values of the memory bank),but in https://github.com/fumin/ntm/blob/master/addressing.go#L527 you computed the grads of the memOp using back propagation,but the grads have never been added to the corresponding parameter(for example in https://github.com/fumin/ntm/blob/master/addressing.go#L288 you computed the gradient for parameter **GammaVal**, but the gradient is not added to **GammaVal** defined in https://github.com/fumin/ntm/blob/master/addressing.go#L222),I hope I made it clearly this time.

BTW, I observe that in the following picture the read and write focus do not exactly match, but more like shifted.Can you give an intuitive explanation of this for me??
![copy20_weights](https://cloud.githubusercontent.com/assets/1770516/11996136/43469afc-aa98-11e5-8af1-7ada3f463ed6.png)

**Comment by fumin** [comment]
Hi Qing

No problem, I get your question this time. So where is the calculated `GammaVal` https://github.com/fumin/ntm/blob/master/addressing.go#L288 used? Well, first of all note that it is a pointer, which means that its newly assigned value can be used by someone else. In this case, from https://github.com/fumin/ntm/blob/master/addressing.go#L519 we see that this newly computed gradient is used by a memory head. But then where is this gradient of a memory head used? From https://github.com/fumin/ntm/blob/master/ntm.go#L155 we see that the head is given by a controller in the forward pass, and therefore its gradients are be used by that controller in the backward pass. And where is the gradients of that controller used? To answer this, we need to first emphasize that all the structures we have talked about, gamma, heads, controller, are actually the "states" of those objects at a particular time step, say t. With this understanding, it turns out that the gradients of the controller at time t is passed back to calculate the gradients at t-1, t-2, and so on, until we to the state at t=0. And this would be the gradients of the entire backpropagation through time process (If you want to learn more about it, the search keyword is BPTT). Perhaps a clearer picture of this process is this; these arrows depict the forward pass, so if we go the reverse direction, we see where a component's gradient is used ![BPTT](https://docs.google.com/drawings/d/1y5IUPfQfPbY4a_zkAB59Gne0qnC4qcI5U52JPQNFbqU/pub?w=967&h=479)

As for why there is an offset of one in the memory head focus picture you linked, my interpretation is that is it due to start-of-sequence symbol at t=0 . You can see the start-of-sequence symbol occupying row number 9 and column number 1 in ![](https://raw.githubusercontent.com/fumin/ntm/master/readme_static/copy20.png)

**Comment by qingyuanxingsi** [comment]
For question 2,my doubt is that why the same bit vector is not written to and read from the same location? From the result, the output at time step t is from the data read by the head at time t-1,right???

**Comment by qingyuanxingsi** [comment]
Thanks for your reply,closing this now!
